variables:
  group: docker-creds

jobs:
- job: Windows
  pool:
    vmImage: win1803
  variables:
    IMAGE_NAME: 'crates-build-env-windows'
  steps:
    - pwsh: Write-Host $(group)
      displayName: Build Docker image
    - pwsh: ./windows/ci/publish.ps1
      displayName: Publish image to Docker Hub
      condition: |
        and(succeeded(),
            eq(variables['Build.SourceBranch'], 'refs/heads/master'),
            ne(variables['Build.Reason'], 'PullRequest'))
      env:
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)
        DOCKER_USERNAME: $(DOCKER_USERNAME)
